services:
  recipes:
    container_name: recipes-app
    build: ./app
    ports: 
      - "8087:8087"
    volumes:
      - .:/recipes
    networks:
      - recipesnet
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.8
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dummy
      MONGO_INITDB_ROOT_PASSWORD: secret
      GOSU_VERSION: "1.17"
      MONGO_MAJOR: "8.0"
      HOME: /data/db
      JSYAML_VERSION: "3.13.1"
      MONGO_VERSION: "8.0.8"
      GLIBC_TUNABLES: glibc.pthread.rseq=0
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "27017:27017"
    volumes:
      - configdb:/data/configdb
      - db:/data/db
    networks:
      - recipesnet

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: mysecretpassword 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - recipesnet

  pgadmin:
    image: dpage/pgadmin4:9.2
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - recipesnet
    depends_on:
      - postgres

  keycloak:
    image: keycloak/keycloak:26.2
    command: start-dev
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: mysecretpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_URL: http://keycloak:8080
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080
      KC_HOSTNAME_STRICT: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - recipesnet

volumes:
  postgres_data:
  configdb:
  db:

networks:
  recipesnet:
    driver: bridge